/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gst_first_example_2_MainActivity */

#ifndef _Included_com_example_gst_first_example_2_MainActivity
#define _Included_com_example_gst_first_example_2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gst_first_example_2_MainActivity
 * Method:    nativeGetGStreamerInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gst_1first_1example_12_MainActivity_nativeGetGStreamerInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
